lock-version = "1.0"
created-by = "pip"

[[packages]]
name = "dirty-equals"
version = "0.11"

[[packages.wheels]]
name = "dirty_equals-0.11-py3-none-any.whl"
url = "https://files.pythonhosted.org/packages/bb/8d/dbff05239043271dbeace563a7686212a3dd517864a35623fe4d4a64ca19/dirty_equals-0.11-py3-none-any.whl"

[packages.wheels.hashes]
sha256 = "b1d7093273fc2f9be12f443a8ead954ef6daaf6746fd42ef3a5616433ee85286"

[[packages]]
name = "iniconfig"
version = "2.3.0"

[[packages.wheels]]
name = "iniconfig-2.3.0-py3-none-any.whl"
url = "https://cdn.jsdelivr.net/pyodide/v314.0.0/full/iniconfig-2.3.0-py3-none-any.whl"

[packages.wheels.hashes]
sha256 = "ccda0e7de68ffc5839cfafeb83a1dad3baf1b4fff385992b1360e51a90efc20d"

[[packages]]
name = "markdown-it-py"
version = "4.2.0"

[[packages.wheels]]
name = "markdown_it_py-4.2.0-py3-none-any.whl"
url = "https://files.pythonhosted.org/packages/b3/81/4da04ced5a082363ecfa159c010d200ecbd959ae410c10c0264a38cac0f5/markdown_it_py-4.2.0-py3-none-any.whl"

[packages.wheels.hashes]
sha256 = "9f7ebbcd14fe59494226453aed97c1070d83f8d24b6fc3a3bcf9a38092641c4a"

[[packages]]
name = "mdurl"
version = "0.1.2"

[[packages.wheels]]
name = "mdurl-0.1.2-py3-none-any.whl"
url = "https://files.pythonhosted.org/packages/b3/38/89ba8ad64ae25be8de66a6d463314cf1eb366222074cfda9ee839c56a4b4/mdurl-0.1.2-py3-none-any.whl"

[packages.wheels.hashes]
sha256 = "84008a41e51615a49fc9966191ff91509e3c40b939176e643fd50a5c2196b8f8"

[[packages]]
name = "packaging"
version = "26.2"

[[packages.wheels]]
name = "packaging-26.2-py3-none-any.whl"
url = "https://files.pythonhosted.org/packages/df/b2/87e62e8c3e2f4b32e5fe99e0b86d576da1312593b39f47d8ceef365e95ed/packaging-26.2-py3-none-any.whl"

[packages.wheels.hashes]
sha256 = "5fc45236b9446107ff2415ce77c807cee2862cb6fac22b8a73826d0693b0980e"

[[packages]]
name = "pluggy"
version = "1.6.0"

[[packages.wheels]]
name = "pluggy-1.6.0-py3-none-any.whl"
url = "https://cdn.jsdelivr.net/pyodide/v314.0.0/full/pluggy-1.6.0-py3-none-any.whl"

[packages.wheels.hashes]
sha256 = "fe7df89b2aba4cc4068a29a393482f0a0c88f69b1bbea4f41b6a730dbfbc355b"

[[packages]]
name = "pygments"
version = "2.20.0"

[[packages.wheels]]
name = "pygments-2.20.0-py3-none-any.whl"
url = "https://cdn.jsdelivr.net/pyodide/v314.0.0/full/pygments-2.20.0-py3-none-any.whl"

[packages.wheels.hashes]
sha256 = "f6a334f8a09102f73df39be89f58a0cb714e994f679ae7bc290ef5209b965ac6"

[[packages]]
name = "pytest"
version = "9.1.0"

[[packages.wheels]]
name = "pytest-9.1.0-py3-none-any.whl"
url = "https://files.pythonhosted.org/packages/8b/5a/ba30a81239b909821b3153e303e7def45178bf353da4f72380e6c5e8793b/pytest-9.1.0-py3-none-any.whl"

[packages.wheels.hashes]
sha256 = "8ebb0e7888bdf2bdfc602ec51f8f62d50200af37356c74e503c79a94f5c81f32"

[[packages]]
name = "pytest-pretty"
version = "1.3.0"

[[packages.wheels]]
name = "pytest_pretty-1.3.0-py3-none-any.whl"
url = "https://files.pythonhosted.org/packages/ab/85/2f97a1b65178b0f11c9c77c35417a4cc5b99a80db90dad4734a129844ea5/pytest_pretty-1.3.0-py3-none-any.whl"

[packages.wheels.hashes]
sha256 = "074b9d5783cef9571494543de07e768a4dda92a3e85118d6c7458c67297159b7"

[[packages]]
name = "rich"
version = "15.0.0"

[[packages.wheels]]
name = "rich-15.0.0-py3-none-any.whl"
url = "https://files.pythonhosted.org/packages/82/3b/64d4899d73f91ba49a8c18a8ff3f0ea8f1c1d75481760df8c68ef5235bf5/rich-15.0.0-py3-none-any.whl"

[packages.wheels.hashes]
sha256 = "33bd4ef74232fb73fe9279a257718407f169c09b78a87ad3d296f548e27de0bb"
