fail_fast: true

repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.0.1
  hooks:
  - id: check-yaml
  - id: check-toml
  - id: end-of-file-fixer
    exclude: '^benches/.*\.json'
  - id: trailing-whitespace
  - id: check-added-large-files

- repo: local
  hooks:
  - id: format-check
    name: Format Check
    entry: cargo fmt
    types: [rust]
    language: system
    pass_filenames: false
  - id: clippy
    name: Clippy
    entry: cargo clippy -- -D warnings -A incomplete_features -W clippy::dbg_macro -W clippy::print_stdout
    types: [rust]
    language: system
    pass_filenames: false
  - id: test
    name: Test
    entry: cargo test --test main
    types: [rust]
    language: system
    pass_filenames: false
